### ISSUE TITLE
Should this work with Raspbian Buster ?

### ISSUE THREAD

**Issue by Noschvie** [tavinus/cloudmanager#2]
Get this error running @RPi Raspbian Buster and NC 18.0.3 as Docker container:
```
pi@baumgarten:~/cloudmanager $ ./cloudmanager.sh -l en --help
/usr/bin/env: „bash\r“: Datei oder Verzeichnis nicht gefunden

```
Any Idea ? Thanks

**Comment by Noschvie** [comment]
Fixed and is working...

**Comment by tavinus** [comment]
> 
> 
> Get this error running @RPI Raspbian Buster and NC 18.0.3 as Docker container:
> 
> ```
> pi@baumgarten:~/cloudmanager $ ./cloudmanager.sh -l en --help
> /usr/bin/env: „bash\r“: Datei oder Verzeichnis nicht gefunden
> ```
> 
> Any Idea ? Thanks

This is weird. Seems like it had Windows line endings instead of unix?  
How did you fix it?
