### ISSUE TITLE
Handle file/folder names with spaces in them

### ISSUE THREAD

**Issue by Noschvie** [tavinus/cloudmanager#3]
How to use the script to create a folder with a blank as part of the name ?

`./cloudmanager.sh makeFolder 'myTestFolder/my sub B'`

Thanks, Norbert

**Comment by tavinus** [comment]
Hi.  
  
~~I have published a new version that adds support to files and folders with spaces in their names.~~  
  
This has always been possible, not sure what your problem was and I made a mistake when testing that made me introduce changes on v0.1.7 which broke the script. So I reverted it all back on v0.1.8.
  
It should work for files and folders with spaces on both source and target locations.  
  
**Names must be quoted or escaped, eg:**
 - `"my file name"`
 - `my\ file\ name`
  
Thanks for letting me know of this issue.  
  
**Please let me know if this works for you.**  
  
Cheers!  :beer:   
Gus

**Comment by Noschvie** [comment]
Hi,
sorry, but the changes v0.1.7 doesn't work:
./cloudmanager_016.sh makeFolder myFolder -> ok
./cloudmanager_016.sh list -> ok

./cloudmanager_017.sh list -> broken (gets empty list)
./cloudmanager_017.sh makeFolder myFolder -> broken

**Comment by tavinus** [comment]
Now that I am revising it better,  
I think the older version was already capable of what you want.   
  
I tested every function before releasing v0.1.7 and all worked fine, but I was actually using the older version that was system installed. Now I am reverting everything back and re-testing everything again.
  
Did you try to create 2 levels of folders at once?  
There is no recursive creation, the parent folder must exist.  
  
So, at v0.1.6
```
./cloudmanager.sh makeFolder 'myTestFolder/my sub B'
```
should work fine, as long as myTestFolder exists and you have permissions to edit it.
  
Another example would be something like
```
cloudmanager mkdir 'test 01'
cloudmanager mkdir 'test 01/test 02'
```
This should also work.  
  
Honestly I am even thinking about just removing v0.1.7 completely.

**Comment by tavinus** [comment]
Yep, this has always been possible and I just released v0.1.8 which reverts the logic to what was on v0.1.6. Works fine here.  
  
```
./cloudmanager.sh makeFolder 'my sub folder'
```
```
./cloudmanager.sh ls
my sub folder
```
```
./cloudmanager.sh del 'my sub folder'
```
Tested all functions without problems.

**Comment by Noschvie** [comment]
Maybe it depends on the NC configuration, NC is running a docker
[https://github.com/nextcloud/docker](url)
[.examples/docker-compose/insecure/postgres/apache/docker-compose.yml](url)
```
pi@baumgarten:~/cloudmanager $ ./cloudmanager_016.sh mkdir 'test 01'
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at 172.18.0.3 Port 80</address>
</body></html>
pi@baumgarten:~/cloudmanager $ ./cloudmanager_016.sh mkdir 'test01'
pi@baumgarten:~/cloudmanager $ ./cloudmanager_016.sh list
Documents
myFolder
myTestFolder
Nextcloud intro.mp4
Nextcloud Manual.pdf
Nextcloud.png
Photos
Readme.md
test01
```

**Comment by tavinus** [comment]
It is weird, should not happen and running from docker or not should not matter.   
Maybe you can duplicate the CURL call and add an `echo` to the start of the line so we can see what it is passing at least? The quotations will be gone when echoing but we can at least have an idea of what is happening.  
  
 - What system are you running cloudmanager from?  
 - Did you try cloudmanager v0.1.8?  
 - Are you running NC behind a proxy?  
    - This should be fine, I run all my instances behind proxies.
 - Do other functions work on names with spaces?  
 - What version of curl do you have?  
  
Can your run from curl directly?
Try this
```
curl -s -u username:password -X MKCOL "https://cloud.domain.tld/remote.php/dav/files/username/folder name to be created"
```
What happens?  
  
**EDIT**
We could also try to replace spaces with `%20` if the above call does not work for you (works fine here).
So it would be:
```
curl -s -u username:password -X MKCOL "https://cloud.domain.tld/remote.php/dav/files/username/folder%20name%20to%20be%20created"
```

**EDIT2** Fixed curl calls URL
**Both calls work fine here.**
  
---  
  
Seems like older versions of curl may have problems with names with blankspaces.  
Getting the answers above may help us create a workaround.

**Comment by Noschvie** [comment]
Replacing spaces with `%20` works fine! Perfect!

`curl -u <username>:<password> -X MKCOL "http://baumgarten.domain.at:8080/remote.php/dav/files/norbert/my%20Folder/my%20Sub%20A"`

```
pi@baumgarten:~/cloudmanager $ curl --version
curl 7.64.0 (arm-unknown-linux-gnueabihf) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

Thanks!

**Comment by tavinus** [comment]
Interesting...   
  
The curl version is above some that I tested, so not sure on that. Maybe arm/pi curl is compiled with different flags or something.  
  
I already have a function to escape URLs in html chars, but it breaks the link for this use case, even though it works on other situations (it does more than just %20).  
  
So I will create an extra function that JUST changes whitespaces to %20 and nothing else (this seems to always work anywhere).  
  
I will try to implement that now.

**EDIT**  
I was thinking now that this could be about language and encoding (utf-8 / iso8859-1 / C / etc).

**Comment by tavinus** [comment]
Hi again.  
  
[I have created a new release, can you get the new version and check if it works for you](https://github.com/tavinus/cloudmanager/releases)?  
  
You should be able to use just quoted or escaped names "my folder", without the need for changing to `%20` yourself (it is done automagically).  
  
Please let me know if it works for you. Should work for any function.

**Comment by Noschvie** [comment]
v0.1.9 successfully tested with NC 18.0.3, works perfect! Thanks and all the best.
